In [ ]:
import pandas as pd

contracts = pd.read_csv("Supplier_Contracts_20260812.csv")
payments = pd.read_csv("Vendor_Payments_(Purchase_Order_Summary)_20260812.csv")

print("Contracts:", contracts.shape)
print("Payments:", payments.shape)

/tmp/ipykernel_1241/2325861835.py:4: DtypeWarning: Columns (20,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  payments = pd.read_csv("Vendor_Payments_(Purchase_Order_Summary)_20260812.csv")

Contracts: (48350, 21)
Payments: (530509, 33)

In [ ]:
print("CONTRACTS COLUMNS")
for i, col in enumerate(contracts.columns):
    print(i, "→", col)

print("\nPAYMENTS COLUMNS")
for i, col in enumerate(payments.columns):
    print(i, "→", col)

CONTRACTS COLUMNS
0 → Contract Number
1 → Contract Title
2 → Term Start Date
3 → Term End Date
4 → Contract Type
5 → Purchasing Authority
6 → Sole Source
7 → Department Code
8 → Department
9 → Supplier Name (Prime Contractor)
10 → Supplier Name
11 → project_team_lbe_status
12 → Non-Profit
13 → Supplier Type
14 → Scope of Work
15 → Contract Awarded Amount
16 → Purchase Orders Outstanding
17 → Payments Made
18 → Remaining Contract Award Amount
19 → data_as_of
20 → data_loaded_at

PAYMENTS COLUMNS
0 → Fiscal Year
1 → Related Govt Units
2 → Organization Group Code
3 → Organization Group
4 → Department Code
5 → Department
6 → Program Code
7 → Program
8 → Character Code
9 → Character
10 → Object Code
11 → Object
12 → Sub-object Code
13 → Sub-object
14 → Fund Type Code
15 → Fund Type
16 → Fund Code
17 → Fund
18 → Fund Category Code
19 → Fund Category
20 → Purchase Order
21 → Supplier & Other Non-Supplier Payees
22 → Vouchers Paid
23 → Vouchers Pending
24 → Encumbrance Balance
25 → Vouchers Pending Retainage
26 → data_as_of
27 → data_loaded_at
28 → Non-Profit Indicator
29 → Contract Number
30 → Contract Title
31 → Purchase Order Date
32 → Purchasing Authority Description

In [ ]:
import pandas as pd

contracts = pd.read_csv("Supplier_Contracts_20260812.csv")

payments = pd.read_csv(
    "Vendor_Payments_(Purchase_Order_Summary)_20260812.csv",
    low_memory=False
)

print("Contracts:", contracts.shape)
print("Payments:", payments.shape)

Contracts: (48350, 21)
Payments: (530509, 33)

In [ ]:
print("CONTRACTS SAMPLE")
display(contracts.head(3))

print("\nPAYMENTS SAMPLE")
display(payments.head(3))

print("\nCONTRACTS DATA TYPES")
print(contracts.dtypes)

print("\nPAYMENTS DATA TYPES")
print(payments.dtypes)

CONTRACTS SAMPLE

,Contract Number,Contract Title,Term Start Date,Term End Date,Contract Type,Purchasing Authority,Sole Source,Department Code,Department,Supplier Name (Prime Contractor),...,project_team_lbe_status,Non-Profit,Supplier Type,Scope of Work,Contract Awarded Amount,Purchase Orders Outstanding,Payments Made,Remaining Contract Award Amount,data_as_of,data_loaded_at
0,NaN,x,2017/07/14,2022/07/14,Construction Contracts,REAL ESTATE - DOCUMENT NOT BID - USING ORDINAN...,NaN,ADM,ADM GSA - City Administrator,KONE INC,...,Non-LBE,NaN,Prime Contractor,Unspecified,"$1,000,000.00",$0.00,$0.00,"$1,000,000.00",2026/05/18 10:42:13 AM,2026/08/10 03:02:37 AM
1,7104.0,AIR-BPAC16000234-K9 TRAINING,2015/07/01,2017/12/31,"Non-Purchasing Contract (Rents, etc.)",OPEN MARKET PURCHASES,NaN,AIR,AIR Airport Commission,TNT K-9 DETECTION TRAINING SERVICES,...,Non-LBE,NaN,Prime Contractor,AIR-BPAC16000234-K9 TRAINING,"$27,000.00",$0.00,$0.00,"$27,000.00",2026/05/18 10:42:13 AM,2026/08/10 03:02:37 AM
2,13005.0,"Nash & Associates, Grant writing services",2018/12/01,2020/11/30,Professional Services and P-Form Contracts,FOR PROFESSIONAL SERVICES CONTRACTS UNDER 10K,NaN,ADP,ADP Adult Probation,NASH & ASSOCIATES,...,Non-LBE,NaN,Prime Contractor,Unspecified,"$9,999.00",$0.00,$0.00,"$9,999.00",2026/05/18 10:42:13 AM,2026/08/10 03:02:37 AM

PAYMENTS SAMPLE

,Fiscal Year,Related Govt Units,Organization Group Code,Organization Group,Department Code,Department,Program Code,Program,Character Code,Character,...,Vouchers Pending,Encumbrance Balance,Vouchers Pending Retainage,data_as_of,data_loaded_at,Non-Profit Indicator,Contract Number,Contract Title,Purchase Order Date,Purchasing Authority Description
0,2024,NO,4,Community Health,DPH,DPH Public Health,OPR,Operating,MTL_SUPP,Materials & Supplies,...,0,0,0,2024/07/30 11:31:31 AM,2026/08/10 02:58:44 AM,NaN,NaN,NaN,2023/06/19,UNIV HEALTHSYSTEMS CONSORTIUM SERVICES - HEALT...
1,2024,NO,2,"Public Works, Transportation & Commerce",PUC,PUC Public Utilities Commsn,CAP,Capital,NON_PERS_SVCS,Non-Personnel Services,...,0,0,0,2024/11/20 11:23:48 AM,2026/08/10 02:58:44 AM,NaN,1.000018e+09,PUC VARIOUS SEWER REPlCMT NO 8,2024/04/17,CONSTRUCTION SERVICES
2,2024,NO,2,"Public Works, Transportation & Commerce",PUC,PUC Public Utilities Commsn,CAP,Capital,NON_PERS_SVCS,Non-Personnel Services,...,0,0,0,2024/06/20 08:33:44 PM,2026/08/10 02:58:44 AM,NaN,1.000017e+09,NaN,2022/12/16,RELEASE AGAINST A CITY OR DEPARTMENTAL BLANK P...

CONTRACTS DATA TYPES
Contract Number                     float64
Contract Title                       object
Term Start Date                      object
Term End Date                        object
Contract Type                        object
Purchasing Authority                 object
Sole Source                          object
Department Code                      object
Department                           object
Supplier Name (Prime Contractor)     object
Supplier Name                        object
project_team_lbe_status              object
Non-Profit                           object
Supplier Type                        object
Scope of Work                        object
Contract Awarded Amount              object
Purchase Orders Outstanding          object
Payments Made                        object
Remaining Contract Award Amount      object
data_as_of                           object
data_loaded_at                       object
dtype: object

PAYMENTS DATA TYPES
Fiscal Year                               int64
Related Govt Units                       object
Organization Group Code                   int64
Organization Group                       object
Department Code                          object
Department                               object
Program Code                             object
Program                                  object
Character Code                           object
Character                                object
Object Code                              object
Object                                   object
Sub-object Code                           int64
Sub-object                               object
Fund Type Code                           object
Fund Type                                object
Fund Code                                object
Fund                                     object
Fund Category Code                        int64
Fund Category                            object
Purchase Order                           object
Supplier & Other Non-Supplier Payees     object
Vouchers Paid                            object
Vouchers Pending                         object
Encumbrance Balance                      object
Vouchers Pending Retainage               object
data_as_of                               object
data_loaded_at                           object
Non-Profit Indicator                     object
Contract Number                         float64
Contract Title                           object
Purchase Order Date                      object
Purchasing Authority Description         object
dtype: object

In [ ]:
print("MISSING VALUES — CONTRACTS")
print(contracts.isna().sum().sort_values(ascending=False).head(10))

print("\nMISSING VALUES — PAYMENTS")
print(payments.isna().sum().sort_values(ascending=False).head(10))

print("\nCONTRACT NUMBER COVERAGE")
print("Contracts with contract number:", contracts["Contract Number"].notna().sum())
print("Payments with contract number:", payments["Contract Number"].notna().sum())

print("\nUNIQUE CONTRACT NUMBERS")
print("Contracts:", contracts["Contract Number"].nunique())
print("Payments:", payments["Contract Number"].nunique())

MISSING VALUES — CONTRACTS
Sole Source             46993
Non-Profit              35712
Term End Date             670
Department Code            56
Department                 56
Purchasing Authority       49
Contract Type              49
Contract Title             49
Term Start Date            49
Scope of Work              49
dtype: int64

MISSING VALUES — PAYMENTS
Non-Profit Indicator                481401
Contract Title                      312869
Contract Number                     312022
Purchasing Authority Description    154477
Purchase Order Date                  72668
Program Code                             1
Program                                  1
Fiscal Year                              0
Related Govt Units                       0
Character                                0
dtype: int64

CONTRACT NUMBER COVERAGE
Contracts with contract number: 48349
Payments with contract number: 218487

UNIQUE CONTRACT NUMBERS
Contracts: 31935
Payments: 11337

In [ ]:
contract_amounts = ["Contract Awarded Amount", "Purchase Orders Outstanding", "Payments Made", "Remaining Contract Award Amount"]
payment_amounts = ["Vouchers Paid", "Vouchers Pending", "Encumbrance Balance", "Vouchers Pending Retainage"]

for col in contract_amounts:
    contracts[col] = contracts[col].str.replace("$", "", regex=False).str.replace(",", "", regex=False).str.strip().replace("", pd.NA).astype(float)

for col in payment_amounts:
    payments[col] = payments[col].str.replace("$", "", regex=False).str.replace(",", "", regex=False).str.strip().replace("", pd.NA).astype(float)

print("Contract amount columns:")
print(contracts[contract_amounts].dtypes)
print("\nPayment amount columns:")
print(payments[payment_amounts].dtypes)

Contract amount columns:
Contract Awarded Amount            float64
Purchase Orders Outstanding        float64
Payments Made                      float64
Remaining Contract Award Amount    float64
dtype: object

Payment amount columns:
Vouchers Paid                 float64
Vouchers Pending              float64
Encumbrance Balance           float64
Vouchers Pending Retainage    float64
dtype: object

In [ ]:
contracts["Contract Number"] = contracts["Contract Number"].apply(lambda x: str(int(x)) if pd.notna(x) else pd.NA)
payments["Contract Number"] = payments["Contract Number"].apply(lambda x: str(int(x)) if pd.notna(x) else pd.NA)

print("Contract ID type:", contracts["Contract Number"].dtype)
print("Payment ID type:", payments["Contract Number"].dtype)
print("Sample contract IDs:", contracts["Contract Number"].dropna().head().tolist())

Contract ID type: object
Payment ID type: object
Sample contract IDs: ['7104', '13005', '7996', '1000000001', '1000000002']

In [ ]:
contract_counts = contracts["Contract Number"].value_counts()

print("Unique contract numbers:", contract_counts.size)
print("Contract numbers appearing more than once:", (contract_counts > 1).sum())
print("Maximum rows for one contract:", contract_counts.max())

print("\nMost repeated contract numbers:")
print(contract_counts.head(10))

Unique contract numbers: 31935
Contract numbers appearing more than once: 2191
Maximum rows for one contract: 198

Most repeated contract numbers:
Contract Number
1000003991    198
1000003968    138
1000031791    104
1000004002     98
1000003997     97
1000003992     91
1000004001     85
1000003996     84
1000004013     82
1000003989     81
Name: count, dtype: int64

In [ ]:
sample_contract = contracts[contracts["Contract Number"] == "1000003991"]

print("Rows for contract 1000003991:", len(sample_contract))
display(sample_contract[[
    "Contract Number",
    "Supplier Name (Prime Contractor)",
    "Supplier Name",
    "Department",
    "Contract Awarded Amount",
    "Payments Made",
    "Remaining Contract Award Amount"
]].head(20))

Rows for contract 1000003991: 198

,Contract Number,Supplier Name (Prime Contractor),Supplier Name,Department,Contract Awarded Amount,Payments Made,Remaining Contract Award Amount
6808,1000003991,AUSTIN WEBCOR JV,ED2,AIR Airport Commission,68835.56,0.0,68835.56
6809,1000003991,AUSTIN WEBCOR JV,HKS,AIR Airport Commission,344177.78,0.0,344177.78
6810,1000003991,AUSTIN WEBCOR JV,VEC,AIR Airport Commission,68835.56,0.0,68835.56
6811,1000003991,AUSTIN WEBCOR JV,ENVISE,AIR Airport Commission,137671.11,0.0,137671.11
6812,1000003991,AUSTIN WEBCOR JV,FIDATO,AIR Airport Commission,15074986.56,0.0,15074986.56
6813,1000003991,AUSTIN WEBCOR JV,TEECOM,AIR Airport Commission,68835.56,0.0,68835.56
6814,1000003991,AUSTIN WEBCOR JV,CITY ID,AIR Airport Commission,68835.56,0.0,68835.56
6815,1000003991,AUSTIN WEBCOR JV,ISEC INC,AIR Airport Commission,5506844.41,0.0,5506844.41
6816,1000003991,AUSTIN WEBCOR JV,A G S INC,AIR Airport Commission,20650666.53,0.0,20650666.53
6817,1000003991,AUSTIN WEBCOR JV,studiomkb,AIR Airport Commission,68835.56,0.0,68835.56
6818,1000003991,AUSTIN WEBCOR JV,DRILL TECH,AIR Airport Commission,1057246.10,0.0,1057246.10
6819,1000003991,AUSTIN WEBCOR JV,PJ'S REBAR,AIR Airport Commission,68835.56,0.0,68835.56
6820,1000003991,AUSTIN WEBCOR JV,M G WEST CO,AIR Airport Commission,8879786.61,0.0,8879786.61
6821,1000003991,AUSTIN WEBCOR JV,AJS PAINTING,AIR Airport Commission,1445546.66,0.0,1445546.66
6822,1000003991,AUSTIN WEBCOR JV,STRUCTUS INC,AIR Airport Commission,68835.56,0.0,68835.56
6823,1000003991,AUSTIN WEBCOR JV,BLAS TRUCKING,AIR Airport Commission,68835.56,0.0,68835.56
6824,1000003991,AUSTIN WEBCOR JV,CONCRETEWORKS,AIR Airport Commission,894862.22,0.0,894862.22
6825,1000003991,AUSTIN WEBCOR JV,NETXPERTS INC,AIR Airport Commission,68835.56,0.0,68835.56
6826,1000003991,AUSTIN WEBCOR JV,"Olivier, Inc.",AIR Airport Commission,68835.56,0.0,68835.56
6827,1000003991,AUSTIN WEBCOR JV,S J ENGINEERS,AIR Airport Commission,137671.11,0.0,137671.11

In [ ]:
contract_view = sample_contract[[
    "Contract Awarded Amount",
    "Payments Made",
    "Remaining Contract Award Amount"
]].sum()

print("Total awarded amount:", contract_view["Contract Awarded Amount"])
print("Total payments made:", contract_view["Payments Made"])
print("Total remaining amount:", contract_view["Remaining Contract Award Amount"])

Total awarded amount: 869627000.53
Total payments made: 778769317.59
Total remaining amount: 90857682.94000001

In [ ]:
contract_payments = payments[payments["Contract Number"].notna()].copy()

contract_spend = contract_payments.groupby("Contract Number").agg(
    FY2024_Spend=("Vouchers Paid", lambda x: x[contract_payments.loc[x.index, "Fiscal Year"].eq(2024)].sum()),
    FY2025_Spend=("Vouchers Paid", lambda x: x[contract_payments.loc[x.index, "Fiscal Year"].eq(2025)].sum()),
    Total_Spend=("Vouchers Paid", "sum"),
    Purchase_Orders=("Purchase Order", "nunique")
).reset_index()

print("Contract-level payment summary:", contract_spend.shape)
display(contract_spend.head())

Contract-level payment summary: (11337, 5)

  Contract Number  FY2024_Spend  FY2025_Spend  Total_Spend  Purchase_Orders
0      1000000014    2187914.13     481177.33   2669091.46               33
1      1000000020          0.00          0.00         0.00                1
2      1000000038          0.00          0.00         0.00                1
3      1000000042    1455264.47     637242.83   2092507.30               49
4      1000000051      84848.16          0.00     84848.16                7

In [ ]:
print("Payment rows with contract numbers:", len(contract_payments))
print("Unique contracts:", contract_payments["Contract Number"].nunique())

print("\nTotal vouchers paid from payment records:",
      contract_payments["Vouchers Paid"].sum())

print("Total spend in contract summary:",
      contract_spend["Total_Spend"].sum())

print("\nDifference:",
      contract_payments["Vouchers Paid"].sum() - contract_spend["Total_Spend"].sum())

Payment rows with contract numbers: 218487
Unique contracts: 11337

Total vouchers paid from payment records: 1036044294079.09
Total spend in contract summary: 1036044294079.09

Difference: 0.0

In [ ]:
payment_contract_ids = set(contract_spend["Contract Number"].dropna())
contract_ids = set(contracts["Contract Number"].dropna())

matched_ids = payment_contract_ids.intersection(contract_ids)

print("Contracts with payment activity:", len(payment_contract_ids))
print("Matching contract records:", len(matched_ids))
print("Unmatched contract IDs:", len(payment_contract_ids - contract_ids))
print("Match rate:", round(len(matched_ids) / len(payment_contract_ids) * 100, 2), "%")

Contracts with payment activity: 11337
Matching contract records: 11110
Unmatched contract IDs: 227
Match rate: 98.0 %

In [ ]:
contract_analysis = contracts.merge(contract_spend, on="Contract Number", how="left")
contract_analysis["Total_Spend"] = contract_analysis["Total_Spend"].fillna(0)
contract_analysis["FY2024_Spend"] = contract_analysis["FY2024_Spend"].fillna(0)
contract_analysis["FY2025_Spend"] = contract_analysis["FY2025_Spend"].fillna(0)
contract_analysis["Purchase_Orders"] = contract_analysis["Purchase_Orders"].fillna(0)

print("Rows in analysis table:", len(contract_analysis))
print("Columns:", len(contract_analysis.columns))
display(contract_analysis.head())

Rows in analysis table: 48350
Columns: 25

,Contract Number,Contract Title,Term Start Date,Term End Date,Contract Type,Purchasing Authority,Sole Source,Department Code,Department,Supplier Name (Prime Contractor),...,Contract Awarded Amount,Purchase Orders Outstanding,Payments Made,Remaining Contract Award Amount,data_as_of,data_loaded_at,FY2024_Spend,FY2025_Spend,Total_Spend,Purchase_Orders
0,<NA>,x,2017/07/14,2022/07/14,Construction Contracts,REAL ESTATE - DOCUMENT NOT BID - USING ORDINAN...,NaN,ADM,ADM GSA - City Administrator,KONE INC,...,1000000.0,0.0,0.00,1000000.00,2026/05/18 10:42:13 AM,2026/08/10 03:02:37 AM,0.00,0.00,0.00,0.0
1,7104,AIR-BPAC16000234-K9 TRAINING,2015/07/01,2017/12/31,"Non-Purchasing Contract (Rents, etc.)",OPEN MARKET PURCHASES,NaN,AIR,AIR Airport Commission,TNT K-9 DETECTION TRAINING SERVICES,...,27000.0,0.0,0.00,27000.00,2026/05/18 10:42:13 AM,2026/08/10 03:02:37 AM,0.00,0.00,0.00,0.0
2,13005,"Nash & Associates, Grant writing services",2018/12/01,2020/11/30,Professional Services and P-Form Contracts,FOR PROFESSIONAL SERVICES CONTRACTS UNDER 10K,NaN,ADP,ADP Adult Probation,NASH & ASSOCIATES,...,9999.0,0.0,0.00,9999.00,2026/05/18 10:42:13 AM,2026/08/10 03:02:37 AM,0.00,0.00,0.00,0.0
3,7996,CHF-GA-Mission YMCA Summer and,2018/07/01,2024/09/13,"Grant Contracts (City as Grantor, previously n...",AUTHORIZED BY GRANT - NOT PURCHASING AUTHORITY,NaN,CHF,CHF Children;Youth & Families,YMCA OF SAN FRANCISCO,...,4843766.0,0.0,4246071.32,597694.68,2026/05/18 10:42:13 AM,2026/08/10 03:02:37 AM,494402.46,160691.11,655093.57,7.0
4,1000000001,FEES FOR ENERGY TRACKING - CLP,2016/08/01,2019/07/30,Purchasing Contract,NO OTHER SOURCE,X,PUC,PUC Public Utilities Commsn,WREGIS,...,5250.0,0.0,3676.41,1573.59,2026/05/18 10:42:13 AM,2026/08/10 03:02:37 AM,0.00,0.00,0.00,0.0

In [ ]:
contract_level = contracts.groupby("Contract Number", dropna=False).agg(
    Contract_Title=("Contract Title", "first"),
    Department=("Department", "first"),
    Contract_Type=("Contract Type", "first"),
    Prime_Contractor=("Supplier Name (Prime Contractor)", "first"),
    Awarded_Amount=("Contract Awarded Amount", "sum"),
    Payments_Made=("Payments Made", "sum"),
    Remaining_Amount=("Remaining Contract Award Amount", "sum")
).reset_index()

contract_level = contract_level.merge(
    contract_spend,
    on="Contract Number",
    how="left"
)

for col in ["FY2024_Spend", "FY2025_Spend", "Total_Spend", "Purchase_Orders"]:
    contract_level[col] = contract_level[col].fillna(0)

print("Contract-level table:", contract_level.shape)
display(contract_level.head())

Contract-level table: (31936, 12)

,Contract Number,Contract_Title,Department,Contract_Type,Prime_Contractor,Awarded_Amount,Payments_Made,Remaining_Amount,FY2024_Spend,FY2025_Spend,Total_Spend,Purchase_Orders
0,1000000001,FEES FOR ENERGY TRACKING - CLP,PUC Public Utilities Commsn,Purchasing Contract,WREGIS,5250.0,3676.41,1573.59,0.0,0.0,0.0,0.0
1,1000000002,ADMINISTRATIVE CHARGES FOR CPS,PUC Public Utilities Commsn,Purchasing Contract,A P X INC,576000.0,400000.00,176000.00,0.0,0.0,0.0,0.0
2,1000000003,ELECTRIC ENERGY AND GREEN ATTR,PUC Public Utilities Commsn,Purchasing Contract,TGP ENERGY MANAGEMENT LLC,965000.0,762433.50,202566.50,0.0,0.0,0.0,0.0
3,1000000004,CLP - RESOURCE ADEQUACY CAPACI,PUC Public Utilities Commsn,Purchasing Contract,CALPEAK POWER LLC,118800.0,75600.00,43200.00,0.0,0.0,0.0,0.0
4,1000000005,CLP - RESOURCE ADEQUACY CAPACI,PUC Public Utilities Commsn,Purchasing Contract,MALAGA POWER LLC,232200.0,147600.00,84600.00,0.0,0.0,0.0,0.0

In [ ]:
contract_level["Utilization_Rate"] = (contract_level["Payments_Made"] / contract_level["Awarded_Amount"] * 100).fillna(0).clip(upper=100)

print("Average utilization:", round(contract_level["Utilization_Rate"].mean(), 2), "%")
print("Median utilization:", round(contract_level["Utilization_Rate"].median(), 2), "%")

contract_level[["Contract Number", "Awarded_Amount", "Payments_Made", "Remaining_Amount", "Utilization_Rate"]].head(10)

Average utilization: 64.56 %
Median utilization: 80.48 %

,Contract Number,Awarded_Amount,Payments_Made,Remaining_Amount,Utilization_Rate
0,1000000001,5250.0,3676.41,1573.59,70.026857
1,1000000002,576000.0,400000.00,176000.00,69.444444
2,1000000003,965000.0,762433.50,202566.50,79.008653
3,1000000004,118800.0,75600.00,43200.00,63.636364
4,1000000005,232200.0,147600.00,84600.00,63.565891
5,1000000006,355300.0,241300.00,114000.00,67.914439
6,1000000007,165000.0,105000.00,60000.00,63.636364
7,1000000009,30808028.0,2639710.44,28168317.56,8.568255
8,1000000010,15873561.0,102556.39,15771004.61,0.646083
9,1000000011,935098.0,0.00,935098.00,0.000000

In [ ]:
contract_level["Utilization_Band"] = pd.cut(contract_level["Utilization_Rate"], bins=[-1, 25, 50, 75, 100], labels=["0-25%", "25-50%", "50-75%", "75-100%"])
print(contract_level["Utilization_Band"].value_counts().sort_index())

Utilization_Band
0-25%       7369
25-50%      3902
50-75%      3784
75-100%    16880
Name: count, dtype: int64

In [ ]:
underused = contract_level[(contract_level["Utilization_Rate"] < 25) & (contract_level["Awarded_Amount"] > 100000)].copy()
underused = underused.sort_values("Awarded_Amount", ascending=False)

print("High-value contracts with utilization below 25%:", len(underused))
underused[["Contract Number", "Contract_Title", "Department", "Prime_Contractor", "Awarded_Amount", "Payments_Made", "Remaining_Amount", "Utilization_Rate"]].head(15)

High-value contracts with utilization below 25%: 4208

,Contract Number,Contract_Title,Department,Prime_Contractor,Awarded_Amount,Payments_Made,Remaining_Amount,Utilization_Rate
10556,1000013810,"DPH-Contracts, Pharmaceuticals",DPH Public Health,MCKESSON PLASMA AND BIOLOGICS LLC,1.466738e+09,1.703035e+08,1.292571e+09,11.611042
31763,1000038171,MTA 1334 Potrero Infrastructure - Project Agre...,MTA Municipal Transprtn Agncy,PRG-Potrero Properties LLC,1.400000e+09,6.500000e+07,1.335000e+09,4.642857
1004,1000001128,6694A SFGH REBUILD CM/GC FORMA,DPW GSA - Public Works,WEBCOR BUILDERS,7.035594e+08,0.000000e+00,7.035594e+08,0.000000
28857,1000034645,PUC_CLP_GONZAGWF_PPA_4782_FY26,PUC Public Utilities Commsn,"Gonzaga Ridge Wind Farm, LLC",6.963059e+08,0.000000e+00,6.861455e+08,0.000000
485,1000000502,PUC CALAVERAS DAM REPLAC PROJ,PUC Public Utilities Commsn,DRAGADOS USA/FLATIRON WEST/SUKUT CNST JV,5.980187e+08,9.522983e+07,5.027889e+08,15.924221
29363,1000035195,SFMTA-2022-40-FTA CBTC,MTA Municipal Transprtn Agncy,HITACHI RAIL GTS USA INC,5.638457e+08,1.191094e+07,5.493407e+08,2.112446
30028,1000036005,DEC ECE Access & Enrollment,DEC Dept of Early Childhood,CHILDREN'S COUNCIL OF SAN FRANCISCO,4.363827e+08,8.151200e+07,3.136012e+08,18.679018
3400,1000005392,TO CERTIFY CONTRACT NO.CPT 713,MTA Municipal Transprtn Agncy,NEW FLYER OF AMERICA INC,4.122704e+08,7.551947e+07,3.367510e+08,18.317945
19189,1000023813,UASI BATEP URTA,DEM Emergency Management,Utility Response Training Associates LLC,3.771440e+08,2.697206e+05,3.768743e+08,0.071517
31572,1000037881,PUC_CLP_SUNZIAS_PPA_6363_FY26,PUC Public Utilities Commsn,SunZia Wind South LLC,3.420000e+08,0.000000e+00,3.325524e+08,0.000000
25106,1000030481,PUC_CPSF_PCC1_4022,PUC Public Utilities Commsn,SOUTHERN CALIFORNIA EDISON CO.,3.012660e+08,4.749567e+07,2.450021e+08,15.765358
30492,1000036566,RET:Investment Management Svcs,RET Retirement System,ARROWSTREET CAPITAL LP,3.000000e+08,6.197963e+06,2.755000e+08,2.065988
22903,1000027949,PUC_CLP_ShareCost_Ormat,PUC Public Utilities Commsn,California Community Power,2.980000e+08,1.496700e+05,2.978086e+08,0.050225
29718,1000035624,PUC Millbrae Campus Improvemnt,PUC Public Utilities Commsn,CLARK CONSTRUCTION GROUP - CALIF LP,2.689329e+08,7.600000e+04,2.679369e+08,0.028260
19588,1000024252,PUC_CLP_PPA_564,PUC Public Utilities Commsn,"Maverick Solar 6, LLC",2.502028e+08,3.800934e+07,2.077978e+08,15.191411

In [ ]:
print("Total awarded value:", round(underused["Awarded_Amount"].sum(), 2))
print("Total payments made:", round(underused["Payments_Made"].sum(), 2))
print("Total remaining value:", round(underused["Remaining_Amount"].sum(), 2))
print("Share of all awarded value:", round(underused["Awarded_Amount"].sum() / contract_level["Awarded_Amount"].sum() * 100, 2), "%")

Total awarded value: 29287793640.27
Total payments made: 2166226130.34
Total remaining value: 23169635639.47
Share of all awarded value: 28.95 %

In [ ]:
department_exposure = underused.groupby("Department").agg(Contracts=("Contract Number", "nunique"),Awarded_Value=("Awarded_Amount", "sum"),Remaining_Value=("Remaining_Amount", "sum")
).sort_values("Remaining_Value", ascending=False).reset_index()

department_exposure["Remaining_Share"] = department_exposure["Remaining_Value"] / underused["Remaining_Amount"].sum() * 100

department_exposure.head(10)

,Department,Contracts,Awarded_Value,Remaining_Value,Remaining_Share
0,PUC Public Utilities Commsn,583,7.318469e+09,6.216437e+09,26.830102
1,MTA Municipal Transprtn Agncy,240,4.706345e+09,4.078696e+09,17.603624
2,DPH Public Health,479,4.321402e+09,3.826278e+09,16.514190
3,ADM GSA - City Administrator,668,2.990106e+09,2.615933e+09,11.290352
4,AIR Airport Commission,422,2.391782e+09,2.140251e+09,9.237309
5,DPW GSA - Public Works,374,1.730324e+09,1.657424e+09,7.153430
6,HSA Human Services Agency,196,7.537811e+08,6.250157e+08,2.697564
7,RET Retirement System,34,5.901715e+08,5.292541e+08,2.284257
8,DEC Dept of Early Childhood,24,6.892013e+08,5.078182e+08,2.191740
9,HOM Homelessness Services,107,5.951347e+08,4.342473e+08,1.874209

In [ ]:
supplier_summary = contract_level.groupby("Prime_Contractor").agg(Contracts=("Contract Number", "nunique"), Awarded_Value=("Awarded_Amount", "sum"), Payments_Made=("Payments_Made", "sum")).sort_values("Awarded_Value", ascending=False).reset_index()
supplier_summary.head(15)

,Prime_Contractor,Contracts,Awarded_Value,Payments_Made
0,REGENTS OF THE UNIVERSITY OF CALIFORNIA,95,2.440960e+09,2.165565e+09
1,MWH CONSTRS & WEBCOR BLDRS A CNST JV,1,2.194283e+09,5.051967e+09
2,HENSEL PHELPS CONSTRUCTION CO,4,2.175762e+09,1.954316e+09
3,TURNER CONSTRUCTION CO,4,2.090231e+09,1.185664e+09
4,CHILDREN'S COUNCIL OF SAN FRANCISCO,33,1.658315e+09,9.540511e+08
5,A P X INC,9,1.573467e+09,6.262087e+08
6,AUSTIN WEBCOR JV,3,1.480362e+09,1.500846e+09
7,CLARK CONSTRUCTION GROUP - CALIF LP,13,1.470543e+09,8.926081e+08
8,MCKESSON PLASMA AND BIOLOGICS LLC,1,1.466738e+09,1.703035e+08
9,PRG-Potrero Properties LLC,1,1.400000e+09,6.500000e+07
10,DEPARTMENT OF SOCIAL SERVICES,7,1.399536e+09,1.338932e+09
11,WEBCOR BUILDERS,8,1.363114e+09,4.571761e+08
12,TUTOR PERINI CORPORATION,1,1.212269e+09,7.130196e+08
13,MCKESSON CORPORATION,6,1.086400e+09,4.699448e+08
14,"Siemens Mobility, Inc.",2,1.015237e+09,6.237446e+08

In [ ]:
supplier_summary["Over_Award"] = supplier_summary["Payments_Made"] > supplier_summary["Awarded_Value"]
print("Suppliers with payments above awarded value:", supplier_summary["Over_Award"].sum())
print("Total suppliers:", len(supplier_summary))

Suppliers with payments above awarded value: 80
Total suppliers: 6646

In [ ]:
supplier_spend = payments[payments["Supplier & Other Non-Supplier Payees"].notna()].groupby("Supplier & Other Non-Supplier Payees").agg(Total_Spend=("Vouchers Paid", "sum"), Purchase_Orders=("Purchase Order", "nunique")).sort_values("Total_Spend", ascending=False).reset_index()

print("Suppliers with payment activity:", len(supplier_spend))
supplier_spend.head(15)

Suppliers with payment activity: 7515

       Supplier & Other Non-Supplier Payees   Total_Spend  Purchase_Orders
0   THE BANK OF NEW YORK MELLON TRUST CO NA  2.028869e+11                7
1              US BANK NATIONAL ASSOCIATION  1.985347e+11               12
2         KAISER FOUNDATION HEALTH PLAN INC  1.863878e+11                1
3              THE DEPOSITORY TRUST COMPANY  1.858778e+11                1
4                      BLUE SHIELD OF CALIF  1.596947e+11                1
5   STATE OF CALIF DEPT OF HEALTH CARE SVCS  5.267522e+10                6
6     WILMINGTON TRUST NATIONAL ASSOCIATION  3.425758e+10                1
7       UNITED HEALTHCARE INSURANCE COMPANY  3.375800e+10                1
8           DELTA DENTAL PLAN OF CALIFORNIA  2.405218e+10                1
9   STATE OF CALIF STATE TREAS CASH MGT DIV  8.565865e+09                1
10          P&A ADMINISTRATIVE SERVICES INC  6.910025e+09                6
11                  ZB National Association  5.928792e+09                1
12                      VISION SERVICE PLAN  4.094111e+09                1
13                               Health Net  3.974808e+09                1
14                     WELLS FARGO BANK N A  3.209105e+09                1

In [ ]:
object_spend = payments.groupby("Object").agg(Total_Spend=("Vouchers Paid", "sum"), Purchase_Orders=("Purchase Order", "nunique")).sort_values("Total_Spend", ascending=False).reset_index()
object_spend.head(20)

                            Object   Total_Spend  Purchase_Orders
0    Debt Interest & Other Charges  5.196821e+11                3
1      HlthSvcFnd-HMO/Dental/Disab  3.403245e+11                1
2          Taxes: Licenses/Permits  7.481225e+10            11344
3                  Debt Redemption  7.477864e+10                1
4     HtlhSvcFnd-City Hlth Plan Ex  7.345745e+10                1
5   Pmt To RefBnd EswAgt Fr CtySou  2.578307e+10                1
6    Professional/Specialized Svcs  1.698459e+10            18642
7    Rent/Lease-Building/Structure  1.516706e+10             1170
8           Other Current Expenses  4.632188e+09            17385
9     HlthSvcFnd-Other Benefit Exp  4.092286e+09                1
10       Community Based Org Srvcs  3.613203e+09             9801
11       Court Fees and Other Comp  2.332721e+09             1383
12             Debt Service Budget  2.083028e+09                3
13                IHSS Ip Payments  1.677552e+09                4
14   Bldg: Structures/Improvements  1.631161e+09              201
15                 Membership Fees  1.608139e+09              225
16          Unemployment Insurance  1.162972e+09                1
17            Loans Issued By City  9.187782e+08              371
18                       Insurance  9.165877e+08               33
19                          Travel  8.593616e+08               68

In [ ]:
procurement_objects = ["Professional/Specialized Svcs", "Rent/Lease-Building/Structure", "Community Based Org Srvcs", "Bldg: Structures/Improvements", "Membership Fees", "Insurance", "Other Current Expenses"]
procurement_payments = payments[payments["Object"].isin(procurement_objects)].copy()
print("Procurement-focused payment rows:", len(procurement_payments))
print("Procurement-focused spend:", round(procurement_payments["Vouchers Paid"].sum(), 2))

Procurement-focused payment rows: 131201
Procurement-focused spend: 44552924609.15

In [ ]:
procurement_department = procurement_payments.groupby("Department").agg(Total_Spend=("Vouchers Paid", "sum"), Purchase_Orders=("Purchase Order", "nunique")).sort_values("Total_Spend", ascending=False).reset_index()
procurement_department.head(15)

                        Department   Total_Spend  Purchase_Orders
0      PUC Public Utilities Commsn  6.127219e+09             8918
1     ADM GSA - City Administrator  5.850981e+09             3096
2        HSS Health Service System  5.013563e+09              125
3                DPH Public Health  4.030355e+09             7652
4                 DPW Public Works  3.250073e+09             3227
5    MTA Municipal Transprtn Agncy  3.213100e+09             1991
6                      SHF Sheriff  2.515866e+09              423
7           AIR Airport Commission  2.261863e+09             1712
8     REC Recreation & Park Commsn  1.980990e+09             1392
9                        MYR Mayor  1.131239e+09             1590
10       HOM Homelessness Services  9.960708e+08             2257
11  ECN Economic & Wrkfrce Dvlpmnt  9.564039e+08             1158
12          JUV Juvenile Probation  8.452268e+08              252
13              LIB Public Library  6.712533e+08              339
14       HSA Human Services Agency  6.664447e+08             2401

In [ ]:
object_summary = payments.groupby("Object").agg(Total_Spend=("Vouchers Paid", "sum"), Transactions=("Vouchers Paid", "size")).sort_values("Total_Spend", ascending=False).reset_index()
object_summary.head(40)

                            Object   Total_Spend  Transactions
0    Debt Interest & Other Charges  5.196821e+11          2902
1      HlthSvcFnd-HMO/Dental/Disab  3.403245e+11           500
2          Taxes: Licenses/Permits  7.481225e+10         28691
3                  Debt Redemption  7.477864e+10           225
4     HtlhSvcFnd-City Hlth Plan Ex  7.345745e+10           400
5   Pmt To RefBnd EswAgt Fr CtySou  2.578307e+10            25
6    Professional/Specialized Svcs  1.698459e+10         51751
7    Rent/Lease-Building/Structure  1.516706e+10          5669
8           Other Current Expenses  4.632188e+09         45626
9     HlthSvcFnd-Other Benefit Exp  4.092286e+09           100
10       Community Based Org Srvcs  3.613203e+09         12673
11       Court Fees and Other Comp  2.332721e+09         10304
12             Debt Service Budget  2.083028e+09            77
13                IHSS Ip Payments  1.677552e+09            28
14   Bldg: Structures/Improvements  1.631161e+09           392
15                 Membership Fees  1.608139e+09         14881
16          Unemployment Insurance  1.162972e+09            50
17            Loans Issued By City  9.187782e+08           473
18                       Insurance  9.165877e+08           209
19                          Travel  8.593616e+08         10742
20                Power for Resale  8.386948e+08           448
21              Equipment Purchase  8.149761e+08          2297
22                        Training  5.591733e+08         15642
23  Maint Svcs-Building & Structur  5.319874e+08          6706
24            Maint Svcs-Equipment  5.123955e+08         10548
25           Other Fringe Benefits  4.674836e+08           300
26                 Rebate Programs  4.583503e+08          3475
27           Retirement Trust Fund  3.699065e+08            50
28     Entertainment and Promotion  3.670276e+08          5206
29  Building/Construction Supplies  3.268663e+08         21595
30                       Utilities  3.015664e+08           873
31        Other Materials/Supplies  2.573934e+08         54646
32             Other Fixed Charges  2.070562e+08           207
33  IHSS Ip Public Authority Admin  2.015295e+08             4
34              Debt Issuance Cost  1.602789e+08          1175
35      Foster Care Transportation  1.581123e+08           129
36  Withdrawal-Normal Contribution  1.576238e+08            50
37         Equipment Mntc Supplies  1.167318e+08         11380
38          Rents/Leases-Equipment  1.139882e+08          4266
39                Fuels/Lubricants  1.039228e+08          1100

In [ ]:
procurement_objects = ["Professional/Specialized Svcs", "Rent/Lease-Building/Structure", "Community Based Org Srvcs", "Bldg: Structures/Improvements", "Membership Fees", "Insurance", "Equipment Purchase", "Training", "Maint Svcs-Building & Structur", "Maint Svcs-Equipment", "Building/Construction Supplies", "Other Materials/Supplies", "Equipment Mntc Supplies", "Rents/Leases-Equipment", "Fuels/Lubricants", "Utilities", "Travel", "Entertainment and Promotion"]

procurement_payments = payments[payments["Object"].isin(procurement_objects)].copy()

print("Procurement transactions:", len(procurement_payments))
print("Procurement spend:", round(procurement_payments["Vouchers Paid"].sum(), 2))
print("Share of all payment spend:", round(procurement_payments["Vouchers Paid"].sum() / payments["Vouchers Paid"].sum() * 100, 2), "%")

Procurement transactions: 230576
Procurement spend: 44786127395.71
Share of all payment spend: 3.82 %

In [ ]:
supplier_spend = procurement_payments.groupby("Supplier & Other Non-Supplier Payees").agg(Total_Spend=("Vouchers Paid", "sum"), Purchase_Orders=("Purchase Order", "nunique")).sort_values("Total_Spend", ascending=False).reset_index()

print("Suppliers:", len(supplier_spend))
supplier_spend.head(15)

Suppliers: 5914

       Supplier & Other Non-Supplier Payees   Total_Spend  Purchase_Orders
0              US BANK NATIONAL ASSOCIATION  1.048667e+10               10
1                      BLUE SHIELD OF CALIF  4.863341e+09                1
2                      WELLS FARGO BANK N A  3.195270e+09                1
3                        ANVIL BUILDERS INC  1.148236e+09               53
4      MWH CONSTRS & WEBCOR BLDRS A CNST JV  9.137104e+08              212
5                 PACIFIC GAS & ELECTRIC CO  9.074308e+08              100
6    STATE OF CALIF -DEPT OF INDL RELATIONS  8.074573e+08                6
7            CALIFORNIA ACADEMY OF SCIENCES  6.861202e+08               10
8                     Single Payment Payees  5.743218e+08                1
9   REGENTS OF THE UNIVERSITY OF CALIFORNIA  5.603139e+08              277
10            HENSEL PHELPS CONSTRUCTION CO  5.442150e+08               20
11                    AMERICAN AIRLINES INC  5.115065e+08                1
12                   TURNER CONSTRUCTION CO  4.148218e+08                7
13            LIBKRA INVESTMENT CORPORATION  3.849346e+08                1
14                         2725 Oakdale LLC  3.398459e+08                1

In [ ]:
supplier_spend["Spend_Share"] = supplier_spend["Total_Spend"] / supplier_spend["Total_Spend"].sum() * 100
supplier_spend["Cumulative_Share"] = supplier_spend["Spend_Share"].cumsum()

top_10_share = supplier_spend.head(10)["Total_Spend"].sum() / supplier_spend["Total_Spend"].sum() * 100
top_20_share = supplier_spend.head(20)["Total_Spend"].sum() / supplier_spend["Total_Spend"].sum() * 100

print("Top 10 supplier spend share:", round(top_10_share, 2), "%")
print("Top 20 supplier spend share:", round(top_20_share, 2), "%")

Top 10 supplier spend share: 53.91 %
Top 20 supplier spend share: 61.64 %

In [ ]:
top_suppliers = supplier_spend.head(10)[["Supplier & Other Non-Supplier Payees", "Total_Spend", "Purchase_Orders", "Spend_Share", "Cumulative_Share"]]
top_suppliers

,Supplier & Other Non-Supplier Payees,Total_Spend,Purchase_Orders,Spend_Share,Cumulative_Share
0,US BANK NATIONAL ASSOCIATION,1.048667e+10,10,23.414989,23.414989
1,BLUE SHIELD OF CALIF,4.863341e+09,1,10.859034,34.274023
2,WELLS FARGO BANK N A,3.195270e+09,1,7.134507,41.408531
3,ANVIL BUILDERS INC,1.148236e+09,53,2.563821,43.972352
4,MWH CONSTRS & WEBCOR BLDRS A CNST JV,9.137104e+08,212,2.040164,46.012516
5,PACIFIC GAS & ELECTRIC CO,9.074308e+08,100,2.026143,48.038659
6,STATE OF CALIF -DEPT OF INDL RELATIONS,8.074573e+08,6,1.802918,49.841577
7,CALIFORNIA ACADEMY OF SCIENCES,6.861202e+08,10,1.531993,51.373570
8,Single Payment Payees,5.743218e+08,1,1.282365,52.655935
9,REGENTS OF THE UNIVERSITY OF CALIFORNIA,5.603139e+08,277,1.251088,53.907023

In [ ]:
supplier_spend.head(30)[["Supplier & Other Non-Supplier Payees", "Total_Spend", "Purchase_Orders"]]

        Supplier & Other Non-Supplier Payees   Total_Spend  Purchase_Orders
0               US BANK NATIONAL ASSOCIATION  1.048667e+10               10
1                       BLUE SHIELD OF CALIF  4.863341e+09                1
2                       WELLS FARGO BANK N A  3.195270e+09                1
3                         ANVIL BUILDERS INC  1.148236e+09               53
4       MWH CONSTRS & WEBCOR BLDRS A CNST JV  9.137104e+08              212
5                  PACIFIC GAS & ELECTRIC CO  9.074308e+08              100
6     STATE OF CALIF -DEPT OF INDL RELATIONS  8.074573e+08                6
7             CALIFORNIA ACADEMY OF SCIENCES  6.861202e+08               10
8                      Single Payment Payees  5.743218e+08                1
9    REGENTS OF THE UNIVERSITY OF CALIFORNIA  5.603139e+08              277
10             HENSEL PHELPS CONSTRUCTION CO  5.442150e+08               20
11                     AMERICAN AIRLINES INC  5.115065e+08                1
12                    TURNER CONSTRUCTION CO  4.148218e+08                7
13             LIBKRA INVESTMENT CORPORATION  3.849346e+08                1
14                          2725 Oakdale LLC  3.398459e+08                1
15                           HEALTHRIGHT 360  2.819532e+08               61
16                     Siemens Mobility Inc.  2.739126e+08               33
17       CHILDREN'S COUNCIL OF SAN FRANCISCO  2.631931e+08               34
18          RICHMOND AREA MULTI-SERVICES INC  2.358491e+08               67
19               Mark Farrell for Mayor 2024  2.148000e+08                1
20                   A&A Health Services LLC  1.636959e+08                6
21                     PCL CONSTRUCTION INC.  1.540710e+08                7
22              BAY AREA COMMUNITY RESOURCES  1.502394e+08              112
23                         BAYVIEW PLAZA LLC  1.452023e+08                8
24   CALIFORNIA COMMUNITY CHOICE ASSOCIATION  1.439208e+08                7
25  EDGEWOOD CENTER FOR CHILDREN AND FAMILES  1.434596e+08               35
26               SUNDT/WALSH A JOINT VENTURE  1.334904e+08              163
27     EAST BAY MUNICIPAL UTILITIES DISTRICT  1.329234e+08                6
28  SAN FRANCISCO PRETRIAL DIVERSION PROJECT  1.313527e+08               40
29                    CROSS COUNTRY STAFFING  1.306521e+08               27

In [ ]:
contractor_summary = contract_level.groupby("Prime_Contractor").agg(Contracts=("Contract Number", "nunique"), Awarded_Value=("Awarded_Amount", "sum"), Remaining_Value=("Remaining_Amount", "sum")).sort_values("Awarded_Value", ascending=False).reset_index()
contractor_summary["Awarded_Share"] = contractor_summary["Awarded_Value"] / contractor_summary["Awarded_Value"].sum() * 100
contractor_summary.head(15)

,Prime_Contractor,Contracts,Awarded_Value,Remaining_Value,Awarded_Share
0,REGENTS OF THE UNIVERSITY OF CALIFORNIA,95,2.440960e+09,1.943608e+08,2.412612
1,MWH CONSTRS & WEBCOR BLDRS A CNST JV,1,2.194283e+09,-3.473140e+09,2.168800
2,HENSEL PHELPS CONSTRUCTION CO,4,2.175762e+09,1.971047e+08,2.150494
3,TURNER CONSTRUCTION CO,4,2.090231e+09,7.172589e+08,2.065957
4,CHILDREN'S COUNCIL OF SAN FRANCISCO,33,1.658315e+09,6.462682e+08,1.639057
5,A P X INC,9,1.573467e+09,8.459615e+08,1.555194
6,AUSTIN WEBCOR JV,3,1.480362e+09,-1.979448e+10,1.463170
7,CLARK CONSTRUCTION GROUP - CALIF LP,13,1.470543e+09,-1.520094e+09,1.453466
8,MCKESSON PLASMA AND BIOLOGICS LLC,1,1.466738e+09,1.292571e+09,1.449704
9,PRG-Potrero Properties LLC,1,1.400000e+09,1.335000e+09,1.383741
10,DEPARTMENT OF SOCIAL SERVICES,7,1.399536e+09,4.164795e+07,1.383283
11,WEBCOR BUILDERS,8,1.363114e+09,8.878199e+08,1.347284
12,TUTOR PERINI CORPORATION,1,1.212269e+09,4.648732e+08,1.198191
13,MCKESSON CORPORATION,6,1.086400e+09,6.111305e+08,1.073784
14,"Siemens Mobility, Inc.",2,1.015237e+09,3.550777e+08,1.003447

In [ ]:
top_5_awarded = contractor_summary.head(5)["Awarded_Value"].sum() / contractor_summary["Awarded_Value"].sum() * 100
top_10_awarded = contractor_summary.head(10)["Awarded_Value"].sum() / contractor_summary["Awarded_Value"].sum() * 100

print("Top 5 contractor share:", round(top_5_awarded, 2), "%")
print("Top 10 contractor share:", round(top_10_awarded, 2), "%")

Top 5 contractor share: 10.44 %
Top 10 contractor share: 17.74 %

In [ ]:
yearly_procurement = procurement_payments.groupby("Fiscal Year").agg(Total_Spend=("Vouchers Paid", "sum"), Transactions=("Vouchers Paid", "size")).reset_index().sort_values("Fiscal Year")
yearly_procurement

   Fiscal Year   Total_Spend  Transactions
0         2024  2.247411e+10        113199
1         2025  2.231202e+10        117377

In [ ]:
yearly_procurement["Avg_Spend_Per_Transaction"] = yearly_procurement["Total_Spend"] / yearly_procurement["Transactions"]
yearly_procurement

   Fiscal Year   Total_Spend  Transactions  Avg_Spend_Per_Transaction
0         2024  2.247411e+10        113199              198536.293884
1         2025  2.231202e+10        117377              190088.496590

In [ ]:
year_object_spend = procurement_payments.groupby(["Fiscal Year", "Object"])["Vouchers Paid"].sum().reset_index()
year_object_spend["Share"] = year_object_spend.groupby("Fiscal Year")["Vouchers Paid"].transform(lambda x: x / x.sum() * 100)
year_object_spend.sort_values(["Fiscal Year", "Vouchers Paid"], ascending=[True, False]).head(20)

    Fiscal Year                          Object  Vouchers Paid      Share
13         2024   Rent/Lease-Building/Structure   8.357136e+09  37.185615
12         2024   Professional/Specialized Svcs   7.743365e+09  34.454602
2          2024       Community Based Org Srvcs   1.755750e+09   7.812322
10         2024                 Membership Fees   8.943770e+08   3.979588
5          2024              Equipment Purchase   5.396784e+08   2.401334
0          2024   Bldg: Structures/Improvements   5.299949e+08   2.358246
16         2024                          Travel   5.153875e+08   2.293250
7          2024                       Insurance   5.088541e+08   2.264179
8          2024  Maint Svcs-Building & Structur   3.224114e+08   1.434590
15         2024                        Training   3.119656e+08   1.388111
9          2024            Maint Svcs-Equipment   2.552726e+08   1.135852
3          2024     Entertainment and Promotion   1.467014e+08   0.652757
17         2024                       Utilities   1.326610e+08   0.590284
1          2024  Building/Construction Supplies   1.248533e+08   0.555543
11         2024        Other Materials/Supplies   1.201249e+08   0.534504
14         2024          Rents/Leases-Equipment   8.061756e+07   0.358713
6          2024                Fuels/Lubricants   6.972063e+07   0.310226
4          2024         Equipment Mntc Supplies   6.523897e+07   0.290285
30         2025   Professional/Specialized Svcs   9.241225e+09  41.418149
31         2025   Rent/Lease-Building/Structure   6.809921e+09  30.521315

In [ ]:
year_object_spend.groupby("Fiscal Year")["Vouchers Paid"].sum()

Fiscal Year
2024    2.247411e+10
2025    2.231202e+10
Name: Vouchers Paid, dtype: float64

In [ ]:
year_object_spend.sort_values(["Fiscal Year", "Vouchers Paid"], ascending=[True, False]).groupby("Fiscal Year").head(10)

    Fiscal Year                          Object  Vouchers Paid      Share
13         2024   Rent/Lease-Building/Structure   8.357136e+09  37.185615
12         2024   Professional/Specialized Svcs   7.743365e+09  34.454602
2          2024       Community Based Org Srvcs   1.755750e+09   7.812322
10         2024                 Membership Fees   8.943770e+08   3.979588
5          2024              Equipment Purchase   5.396784e+08   2.401334
0          2024   Bldg: Structures/Improvements   5.299949e+08   2.358246
16         2024                          Travel   5.153875e+08   2.293250
7          2024                       Insurance   5.088541e+08   2.264179
8          2024  Maint Svcs-Building & Structur   3.224114e+08   1.434590
15         2024                        Training   3.119656e+08   1.388111
30         2025   Professional/Specialized Svcs   9.241225e+09  41.418149
31         2025   Rent/Lease-Building/Structure   6.809921e+09  30.521315
20         2025       Community Based Org Srvcs   1.857453e+09   8.324898
18         2025   Bldg: Structures/Improvements   1.101166e+09   4.935305
28         2025                 Membership Fees   7.137622e+08   3.199003
25         2025                       Insurance   4.077336e+08   1.827417
34         2025                          Travel   3.439741e+08   1.541654
23         2025              Equipment Purchase   2.752977e+08   1.233854
27         2025            Maint Svcs-Equipment   2.571229e+08   1.152397
33         2025                        Training   2.472077e+08   1.107958

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
contracts.to_csv("/content/drive/MyDrive/contracts_clean.csv", index=False)
payments.to_csv("/content/drive/MyDrive/payments_clean.csv", index=False)
procurement_payments.to_csv("/content/drive/MyDrive/procurement_payments_clean.csv", index=False)
print("All three files saved to Google Drive")

All three files saved to Google Drive